### ISSUE TITLE
最新版lsp被提示过期

### ISSUE THREAD

**Issue by soulpursuit** [Xposed-Modules-Repo/com.yifeplayte.maxfreeform#2]
![Screenshot_2022-06-26-09-27-44-755_com yifeplayte maxfreeform](https://user-images.githubusercontent.com/48674277/175795574-f4e73aee-40a7-433a-ab48-9e6bb68eaa70.jpg)
![Screenshot_2022-06-26-09-27-48-754_com miui securitycenter](https://user-images.githubusercontent.com/48674277/175795576-b36b96da-8420-4c94-be23-97938946b22a.jpg)
![Screenshot_2022-06-26-09-27-57-998_com android shell](https://user-images.githubusercontent.com/48674277/175795578-3a27cd36-2e92-4c9b-ad9f-feb95cfb4665.jpg)

**Comment by YifePlayte** [comment]
请尝试在lsp里重新开关激活本模块。这是个未知bug，我无法修复。
